In [49]:
import numpy as np

l=[2,3,4,5]
a=np.array(l)
type(a)
b=10
print(a+b)
ar1=np.array([10,20,4.5])
print(ar1+10)

[12 13 14 15]
[20.  30.  14.5]


In [50]:
ones=np.ones((2,3,4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [51]:
import random
y=random.uniform(3,4)
print(y)

3.731788326098568


In [52]:
ar1=np.array([[10,20,30],[20,30,50]])
ar1.shape

(2, 3)

In [53]:
x=np.array([10])
x.shape

(1,)

In [54]:
ar1+x

array([[20, 30, 40],
       [30, 40, 60]])

In [55]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([10,20,40])

In [56]:
np.add(x,y)

array([[11, 22, 43],
       [14, 25, 46]])

In [57]:
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
d=np.arange(18).reshape(2,3,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [59]:
arr = np.array([[0,1,2], [3,4,5],[6,7,8]])
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [60]:
arr[1:,:1]

array([[3],
       [6]])

In [61]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8])

In [62]:
arr1=np.array([1,3,4])
arr2=np.array([2,4,5])
rs=np.dot(arr1,arr2)
print(rs)

34


In [63]:
a=np.array([[20,30],[2,4]])
c=np.array([10,50])
np.linalg.solve(a,c)

array([-73.,  49.])

In [64]:
np.random.rand(2,10,2)

array([[[0.41418701, 0.64953516],
        [0.7251527 , 0.02402662],
        [0.73105875, 0.27551962],
        [0.50920027, 0.01204037],
        [0.68614197, 0.63340998],
        [0.08550301, 0.71746904],
        [0.42727049, 0.44003941],
        [0.18311485, 0.48145078],
        [0.00310089, 0.64569633],
        [0.73260291, 0.16180757]],

       [[0.74533352, 0.37897349],
        [0.43865903, 0.18165578],
        [0.34546269, 0.91405482],
        [0.98002992, 0.53236561],
        [0.26725586, 0.99722384],
        [0.5998439 , 0.00723024],
        [0.22523695, 0.41335232],
        [0.95276268, 0.55801233],
        [0.29940534, 0.29655737],
        [0.53100624, 0.06718011]]])

In [65]:
np.random.randint(1,100,size=10)

array([23, 27, 52, 62, 59, 64, 70,  8, 61, 22])

In [66]:
np.random.choice(6,3,replace=False)

array([2, 0, 4])

In [67]:
import pandas as pd
s=pd.Series([10,2,3,'Data',5.5])
s

0      10
1       2
2       3
3    Data
4     5.5
dtype: object

In [68]:
data={
    'score':[100,200],
    'result':['pass','fail']
}

df=pd.DataFrame(data)
df

score result
0    100   pass
1    200   fail

In [69]:
dates=pd.date_range('2020-10-11',periods=7,freq='Y')
dates

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31', '2025-12-31', '2026-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [70]:
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

ValueError: Shape of passed values is (6, 4), indices imply (7, 4)

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [71]:
data=pd.read_csv("police.csv")
data.head()

stop_date stop_time  county_name driver_gender  driver_age_raw  \
0  2005-01-02     01:55          NaN             M          1985.0   
1  2005-01-18     08:15          NaN             M          1965.0   
2  2005-01-23     23:15          NaN             M          1972.0   
3  2005-02-20     17:15          NaN             M          1986.0   
4  2005-03-14     10:00          NaN             F          1984.0   

   driver_age driver_race     violation_raw violation  search_conducted  \
0        20.0       White          Speeding  Speeding             False   
1        40.0       White          Speeding  Speeding             False   
2        33.0       White          Speeding  Speeding             False   
3        19.0       White  Call for Service     Other             False   
4        21.0       White          Speeding  Speeding             False   

  search_type   stop_outcome is_arrested stop_duration  drugs_related_stop  
0         NaN       Citation       False      0-15 Min               False  
1         NaN       Citation       False      0-15 Min               False  
2         NaN       Citation       False      0-15 Min               False  
3         NaN  Arrest Driver        True     16-30 Min               False  
4         NaN       Citation       False      0-15 Min               False

In [ ]:
data.head(10)

stop_date stop_time  county_name driver_gender  driver_age_raw  \
0  2005-01-02     01:55          NaN             M          1985.0   
1  2005-01-18     08:15          NaN             M          1965.0   
2  2005-01-23     23:15          NaN             M          1972.0   
3  2005-02-20     17:15          NaN             M          1986.0   
4  2005-03-14     10:00          NaN             F          1984.0   
5  2005-03-23     09:45          NaN             M          1982.0   
6  2005-04-01     17:30          NaN             M          1969.0   
7  2005-06-06     13:20          NaN             F          1986.0   
8  2005-07-13     10:15          NaN             M          1970.0   
9  2005-07-13     15:45          NaN             M          1970.0   

   driver_age driver_race                   violation_raw  violation  \
0        20.0       White                        Speeding   Speeding   
1        40.0       White                        Speeding   Speeding   
2        33.0       White                        Speeding   Speeding   
3        19.0       White                Call for Service      Other   
4        21.0       White                        Speeding   Speeding   
5        23.0       Black  Equipment/Inspection Violation  Equipment   
6        36.0       White                        Speeding   Speeding   
7        19.0       White                        Speeding   Speeding   
8        35.0       Black                        Speeding   Speeding   
9        35.0       White                        Speeding   Speeding   

   search_conducted search_type   stop_outcome is_arrested stop_duration  \
0             False         NaN       Citation       False      0-15 Min   
1             False         NaN       Citation       False      0-15 Min   
2             False         NaN       Citation       False      0-15 Min   
3             False         NaN  Arrest Driver        True     16-30 Min   
4             False         NaN       Citation       False      0-15 Min   
5             False         NaN       Citation       False      0-15 Min   
6             False         NaN       Citation       False      0-15 Min   
7             False         NaN       Citation       False      0-15 Min   
8             False         NaN       Citation       False      0-15 Min   
9             False         NaN       Citation       False      0-15 Min   

   drugs_related_stop  
0               False  
1               False  
2               False  
3               False  
4               False  
5               False  
6               False  
7               False  
8               False  
9               False

In [ ]:
data.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [ ]:
data.drop(['county_name'],axis=1,inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   stop_date           91741 non-null  object 
 1   stop_time           91741 non-null  object 
 2   driver_gender       86406 non-null  object 
 3   driver_age_raw      86414 non-null  float64
 4   driver_age          86120 non-null  float64
 5   driver_race         86408 non-null  object 
 6   violation_raw       86408 non-null  object 
 7   violation           86408 non-null  object 
 8   search_conducted    91741 non-null  bool   
 9   search_type         3196 non-null   object 
 10  stop_outcome        86408 non-null  object 
 11  is_arrested         86408 non-null  object 
 12  stop_duration       86408 non-null  object 
 13  drugs_related_stop  91741 non-null  bool   
dtypes: bool(2), float64(2), object(10)
memory usage: 8.6+ MB


In [ ]:
data['driver_gender'].fillna(data['driver_gender'].mode,inplace=True)
data

stop_date stop_time driver_gender  driver_age_raw  driver_age  \
0      2005-01-02     01:55             M          1985.0        20.0   
1      2005-01-18     08:15             M          1965.0        40.0   
2      2005-01-23     23:15             M          1972.0        33.0   
3      2005-02-20     17:15             M          1986.0        19.0   
4      2005-03-14     10:00             F          1984.0        21.0   
...           ...       ...           ...             ...         ...   
91736  2015-12-31     20:27             M          1986.0        29.0   
91737  2015-12-31     20:35             F          1982.0        33.0   
91738  2015-12-31     20:45             M          1992.0        23.0   
91739  2015-12-31     21:42             M          1993.0        22.0   
91740  2015-12-31     22:46             M          1959.0        56.0   

      driver_race                   violation_raw         violation  \
0           White                        Speeding          Speeding   
1           White                        Speeding          Speeding   
2           White                        Speeding          Speeding   
3           White                Call for Service             Other   
4           White                        Speeding          Speeding   
...           ...                             ...               ...   
91736       White                        Speeding          Speeding   
91737       White  Equipment/Inspection Violation         Equipment   
91738       White         Other Traffic Violation  Moving violation   
91739       White                        Speeding          Speeding   
91740    Hispanic                        Speeding          Speeding   

       search_conducted search_type   stop_outcome is_arrested stop_duration  \
0                 False         NaN       Citation       False      0-15 Min   
1                 False         NaN       Citation       False      0-15 Min   
2                 False         NaN       Citation       False      0-15 Min   
3                 False         NaN  Arrest Driver        True     16-30 Min   
4                 False         NaN       Citation       False      0-15 Min   
...                 ...         ...            ...         ...           ...   
91736             False         NaN        Warning       False      0-15 Min   
91737             False         NaN        Warning       False      0-15 Min   
91738             False         NaN        Warning       False      0-15 Min   
91739             False         NaN       Citation       False      0-15 Min   
91740             False         NaN       Citation       False      0-15 Min   

       drugs_related_stop  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
91736               False  
91737               False  
91738               False  
91739               False  
91740               False  

[91741 rows x 14 columns]

In [ ]:
data['driver_age'].fillna(data['driver_age'].mean,inplace=True)
data

stop_date stop_time driver_gender  driver_age_raw driver_age  \
0      2005-01-02     01:55             M          1985.0       20.0   
1      2005-01-18     08:15             M          1965.0       40.0   
2      2005-01-23     23:15             M          1972.0       33.0   
3      2005-02-20     17:15             M          1986.0       19.0   
4      2005-03-14     10:00             F          1984.0       21.0   
...           ...       ...           ...             ...        ...   
91736  2015-12-31     20:27             M          1986.0       29.0   
91737  2015-12-31     20:35             F          1982.0       33.0   
91738  2015-12-31     20:45             M          1992.0       23.0   
91739  2015-12-31     21:42             M          1993.0       22.0   
91740  2015-12-31     22:46             M          1959.0       56.0   

      driver_race                   violation_raw         violation  \
0           White                        Speeding          Speeding   
1           White                        Speeding          Speeding   
2           White                        Speeding          Speeding   
3           White                Call for Service             Other   
4           White                        Speeding          Speeding   
...           ...                             ...               ...   
91736       White                        Speeding          Speeding   
91737       White  Equipment/Inspection Violation         Equipment   
91738       White         Other Traffic Violation  Moving violation   
91739       White                        Speeding          Speeding   
91740    Hispanic                        Speeding          Speeding   

       search_conducted search_type   stop_outcome is_arrested stop_duration  \
0                 False         NaN       Citation       False      0-15 Min   
1                 False         NaN       Citation       False      0-15 Min   
2                 False         NaN       Citation       False      0-15 Min   
3                 False         NaN  Arrest Driver        True     16-30 Min   
4                 False         NaN       Citation       False      0-15 Min   
...                 ...         ...            ...         ...           ...   
91736             False         NaN        Warning       False      0-15 Min   
91737             False         NaN        Warning       False      0-15 Min   
91738             False         NaN        Warning       False      0-15 Min   
91739             False         NaN       Citation       False      0-15 Min   
91740             False         NaN       Citation       False      0-15 Min   

       drugs_related_stop  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
91736               False  
91737               False  
91738               False  
91739               False  
91740               False  

[91741 rows x 14 columns]

In [ ]:
data.groupby('driver_gender').agg(np)

In [ ]:
data.loc[21:26,['driver_gender','is_arrested']]

driver_gender is_arrested
21                                                  M       False
22                                                  M        True
23                                                  F       False
24                                                  M        True
25  <bound method Series.mode of 0        M\n1    ...         NaN
26                                                  M       False

In [72]:
data['driver_gender'].fillna(data['driver_gender'].mode()[0],inplace=True)
data

stop_date stop_time  county_name driver_gender  driver_age_raw  \
0      2005-01-02     01:55          NaN             M          1985.0   
1      2005-01-18     08:15          NaN             M          1965.0   
2      2005-01-23     23:15          NaN             M          1972.0   
3      2005-02-20     17:15          NaN             M          1986.0   
4      2005-03-14     10:00          NaN             F          1984.0   
...           ...       ...          ...           ...             ...   
91736  2015-12-31     20:27          NaN             M          1986.0   
91737  2015-12-31     20:35          NaN             F          1982.0   
91738  2015-12-31     20:45          NaN             M          1992.0   
91739  2015-12-31     21:42          NaN             M          1993.0   
91740  2015-12-31     22:46          NaN             M          1959.0   

       driver_age driver_race                   violation_raw  \
0            20.0       White                        Speeding   
1            40.0       White                        Speeding   
2            33.0       White                        Speeding   
3            19.0       White                Call for Service   
4            21.0       White                        Speeding   
...           ...         ...                             ...   
91736        29.0       White                        Speeding   
91737        33.0       White  Equipment/Inspection Violation   
91738        23.0       White         Other Traffic Violation   
91739        22.0       White                        Speeding   
91740        56.0    Hispanic                        Speeding   

              violation  search_conducted search_type   stop_outcome  \
0              Speeding             False         NaN       Citation   
1              Speeding             False         NaN       Citation   
2              Speeding             False         NaN       Citation   
3                 Other             False         NaN  Arrest Driver   
4              Speeding             False         NaN       Citation   
...                 ...               ...         ...            ...   
91736          Speeding             False         NaN        Warning   
91737         Equipment             False         NaN        Warning   
91738  Moving violation             False         NaN        Warning   
91739          Speeding             False         NaN       Citation   
91740          Speeding             False         NaN       Citation   

      is_arrested stop_duration  drugs_related_stop  
0           False      0-15 Min               False  
1           False      0-15 Min               False  
2           False      0-15 Min               False  
3            True     16-30 Min               False  
4           False      0-15 Min               False  
...           ...           ...                 ...  
91736       False      0-15 Min               False  
91737       False      0-15 Min               False  
91738       False      0-15 Min               False  
91739       False      0-15 Min               False  
91740       False      0-15 Min               False  

[91741 rows x 15 columns]

In [75]:
data.sort_values(by=['driver_age'])


stop_date stop_time  county_name driver_gender  driver_age_raw  \
18357  2007-07-04     00:40          NaN             F          1992.0   
17771  2007-06-11     12:30          NaN             M          1992.0   
45988  2010-11-10     19:39          NaN             F          1995.0   
10500  2006-09-30     01:30          NaN             M          1991.0   
25294  2008-04-21     11:19          NaN             M          1993.0   
...           ...       ...          ...           ...             ...   
91637  2015-12-27     09:41          NaN             M             NaN   
91660  2015-12-28     02:28          NaN             M             NaN   
91674  2015-12-28     12:01          NaN             M             NaN   
91710  2015-12-30     13:27          NaN             M             NaN   
91713  2015-12-30     17:07          NaN             M             NaN   

       driver_age driver_race            violation_raw         violation  \
18357        15.0       White  Other Traffic Violation  Moving violation   
17771        15.0       White                 Speeding          Speeding   
45988        15.0       White  Other Traffic Violation  Moving violation   
10500        15.0       Black  Other Traffic Violation  Moving violation   
25294        15.0    Hispanic  Other Traffic Violation  Moving violation   
...           ...         ...                      ...               ...   
91637         NaN         NaN                      NaN               NaN   
91660         NaN         NaN                      NaN               NaN   
91674         NaN         NaN                      NaN               NaN   
91710         NaN         NaN                      NaN               NaN   
91713         NaN         NaN                      NaN               NaN   

       search_conducted         search_type   stop_outcome is_arrested  \
18357             False                 NaN  Arrest Driver        True   
17771             False                 NaN       Citation       False   
45988             False                 NaN       Citation       False   
10500             False                 NaN  Arrest Driver        True   
25294              True  Incident to Arrest  Arrest Driver        True   
...                 ...                 ...            ...         ...   
91637             False                 NaN            NaN         NaN   
91660             False                 NaN            NaN         NaN   
91674             False                 NaN            NaN         NaN   
91710             False                 NaN            NaN         NaN   
91713             False                 NaN            NaN         NaN   

      stop_duration  drugs_related_stop  
18357      0-15 Min               False  
17771      0-15 Min               False  
45988     16-30 Min               False  
10500       30+ Min               False  
25294       30+ Min               False  
...             ...                 ...  
91637           NaN               False  
91660           NaN               False  
91674           NaN               False  
91710           NaN               False  
91713           NaN               False  

[91741 rows x 15 columns]

In [78]:
data.query("driver_age > 20").head()


stop_date stop_time  county_name driver_gender  driver_age_raw  \
1  2005-01-18     08:15          NaN             M          1965.0   
2  2005-01-23     23:15          NaN             M          1972.0   
4  2005-03-14     10:00          NaN             F          1984.0   
5  2005-03-23     09:45          NaN             M          1982.0   
6  2005-04-01     17:30          NaN             M          1969.0   

   driver_age driver_race                   violation_raw  violation  \
1        40.0       White                        Speeding   Speeding   
2        33.0       White                        Speeding   Speeding   
4        21.0       White                        Speeding   Speeding   
5        23.0       Black  Equipment/Inspection Violation  Equipment   
6        36.0       White                        Speeding   Speeding   

   search_conducted search_type stop_outcome is_arrested stop_duration  \
1             False         NaN     Citation       False      0-15 Min   
2             False         NaN     Citation       False      0-15 Min   
4             False         NaN     Citation       False      0-15 Min   
5             False         NaN     Citation       False      0-15 Min   
6             False         NaN     Citation       False      0-15 Min   

   drugs_related_stop  
1               False  
2               False  
4               False  
5               False  
6               False

In [87]:
data.query("driver_age > 20 and driver_race == 'White'").head()


stop_date stop_time  county_name driver_gender  driver_age_raw  \
1  2005-01-18     08:15          NaN             M          1965.0   
2  2005-01-23     23:15          NaN             M          1972.0   
4  2005-03-14     10:00          NaN             F          1984.0   
6  2005-04-01     17:30          NaN             M          1969.0   
9  2005-07-13     15:45          NaN             M          1970.0   

   driver_age driver_race violation_raw violation  search_conducted  \
1        40.0       White      Speeding  Speeding             False   
2        33.0       White      Speeding  Speeding             False   
4        21.0       White      Speeding  Speeding             False   
6        36.0       White      Speeding  Speeding             False   
9        35.0       White      Speeding  Speeding             False   

  search_type stop_outcome is_arrested stop_duration  drugs_related_stop  
1         NaN     Citation       False      0-15 Min               False  
2         NaN     Citation       False      0-15 Min               False  
4         NaN     Citation       False      0-15 Min               False  
6         NaN     Citation       False      0-15 Min               False  
9         NaN     Citation       False      0-15 Min               False

In [88]:
data.set_index('search_type')

stop_date stop_time  county_name driver_gender  driver_age_raw  \
search_type                                                                    
NaN          2005-01-02     01:55          NaN             M          1985.0   
NaN          2005-01-18     08:15          NaN             M          1965.0   
NaN          2005-01-23     23:15          NaN             M          1972.0   
NaN          2005-02-20     17:15          NaN             M          1986.0   
NaN          2005-03-14     10:00          NaN             F          1984.0   
...                 ...       ...          ...           ...             ...   
NaN          2015-12-31     20:27          NaN             M          1986.0   
NaN          2015-12-31     20:35          NaN             F          1982.0   
NaN          2015-12-31     20:45          NaN             M          1992.0   
NaN          2015-12-31     21:42          NaN             M          1993.0   
NaN          2015-12-31     22:46          NaN             M          1959.0   

             driver_age driver_race                   violation_raw  \
search_type                                                           
NaN                20.0       White                        Speeding   
NaN                40.0       White                        Speeding   
NaN                33.0       White                        Speeding   
NaN                19.0       White                Call for Service   
NaN                21.0       White                        Speeding   
...                 ...         ...                             ...   
NaN                29.0       White                        Speeding   
NaN                33.0       White  Equipment/Inspection Violation   
NaN                23.0       White         Other Traffic Violation   
NaN                22.0       White                        Speeding   
NaN                56.0    Hispanic                        Speeding   

                    violation  search_conducted   stop_outcome is_arrested  \
search_type                                                                  
NaN                  Speeding             False       Citation       False   
NaN                  Speeding             False       Citation       False   
NaN                  Speeding             False       Citation       False   
NaN                     Other             False  Arrest Driver        True   
NaN                  Speeding             False       Citation       False   
...                       ...               ...            ...         ...   
NaN                  Speeding             False        Warning       False   
NaN                 Equipment             False        Warning       False   
NaN          Moving violation             False        Warning       False   
NaN                  Speeding             False       Citation       False   
NaN                  Speeding             False       Citation       False   

            stop_duration  drugs_related_stop  
search_type                                    
NaN              0-15 Min               False  
NaN              0-15 Min               False  
NaN              0-15 Min               False  
NaN             16-30 Min               False  
NaN              0-15 Min               False  
...                   ...                 ...  
NaN              0-15 Min               False  
NaN              0-15 Min               False  
NaN              0-15 Min               False  
NaN              0-15 Min               False  
NaN              0-15 Min               False  

[91741 rows x 14 columns]

In [92]:
data.duplicated().sum()

479

In [100]:
from datetime import datetime

def age(driver_age_raw):
    current_year = datetime.now().year  
    return current_year - driver_age_raw  

data['driver_age'] = data['driver_age_raw'].apply(age)
data.head()



stop_date stop_time  county_name driver_gender  driver_age_raw  \
0  2005-01-02     01:55          NaN             M          1985.0   
1  2005-01-18     08:15          NaN             M          1965.0   
2  2005-01-23     23:15          NaN             M          1972.0   
3  2005-02-20     17:15          NaN             M          1986.0   
4  2005-03-14     10:00          NaN             F          1984.0   

   driver_age driver_race     violation_raw violation  search_conducted  \
0        40.0       White          Speeding  Speeding             False   
1        60.0       White          Speeding  Speeding             False   
2        53.0       White          Speeding  Speeding             False   
3        39.0       White  Call for Service     Other             False   
4        41.0       White          Speeding  Speeding             False   

  search_type   stop_outcome is_arrested stop_duration  drugs_related_stop  
0         NaN       Citation       False      0-15 Min               False  
1         NaN       Citation       False      0-15 Min               False  
2         NaN       Citation       False      0-15 Min               False  
3         NaN  Arrest Driver        True     16-30 Min               False  
4         NaN       Citation       False      0-15 Min               False

In [102]:
data['driver_age'] = data['driver_age_raw'].apply(lambda x: datetime.now().year - x)
data.head()

stop_date stop_time  county_name driver_gender  driver_age_raw  \
0  2005-01-02     01:55          NaN             M          1985.0   
1  2005-01-18     08:15          NaN             M          1965.0   
2  2005-01-23     23:15          NaN             M          1972.0   
3  2005-02-20     17:15          NaN             M          1986.0   
4  2005-03-14     10:00          NaN             F          1984.0   

   driver_age driver_race     violation_raw violation  search_conducted  \
0        40.0       White          Speeding  Speeding             False   
1        60.0       White          Speeding  Speeding             False   
2        53.0       White          Speeding  Speeding             False   
3        39.0       White  Call for Service     Other             False   
4        41.0       White          Speeding  Speeding             False   

  search_type   stop_outcome is_arrested stop_duration  drugs_related_stop  
0         NaN       Citation       False      0-15 Min               False  
1         NaN       Citation       False      0-15 Min               False  
2         NaN       Citation       False      0-15 Min               False  
3         NaN  Arrest Driver        True     16-30 Min               False  
4         NaN       Citation       False      0-15 Min               False

In [106]:
pd.crosstab(data['search_conducted'],data['driver_gender'],normalize=True)

driver_gender            F         M
search_conducted                    
False             0.251142  0.714021
True              0.005134  0.029703

In [108]:
data1=pd.read_csv('tips.csv')
data1.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [128]:
average_tip_by_size = data1.groupby("size")["tip"].mean()

average_tip_per_person = average_tip_by_size / average_tip_by_size.index

highest_tipping_size = average_tip_per_person.idxmax()

print(average_tip_per_person)
print(average_tip_by_size)
print(highest_tipping_size)

size
1    1.437500
2    1.291154
3    1.131053
4    1.033851
5    0.805600
6    0.870833
dtype: float64
size
1    1.437500
2    2.582308
3    3.393158
4    4.135405
5    4.028000
6    5.225000
Name: tip, dtype: float64
1


In [ ]:
from sqlalchemy import create_engine
import pymysql
db={
    'name':'fil',
    'user':'root',
    'password':'chessChess2*2*',
    'host':'localhost',
    'port':3306

}
from sqlalchemy import create_engine
engine1 = create_engine("mysql+pymysql://root:chessChess2*2*@localhost/fil")

data1.to_sql(name="tips", con=engine1, if_exists="replace", index=False)


ModuleNotFoundError: No module named 'pymysql'