In [2]:
import numpy as np

l=[2,3,4,5]
a=np.array(l)
type(a)
b=10
print(a+b)
ar1=np.array([10,20,4.5])
print(ar1+10)

[12 13 14 15]
[20.  30.  14.5]


In [3]:
ones=np.ones((2,3,4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [4]:
import random
y=random.uniform(3,4)
print(y)

3.9299552364191266


In [5]:
ar1=np.array([[10,20,30],[20,30,50]])
ar1.shape

(2, 3)

In [6]:
x=np.array([10])
x.shape

(1,)

In [7]:
ar1+x

array([[20, 30, 40],
       [30, 40, 60]])

In [8]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([10,20,40])

In [9]:
np.add(x,y)

array([[11, 22, 43],
       [14, 25, 46]])

In [10]:
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d=np.arange(18).reshape(2,3,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [12]:
arr = np.array([[0,1,2], [3,4,5],[6,7,8]])
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
arr[1:,:1]

array([[3],
       [6]])

In [14]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8])

In [15]:
arr1=np.array([1,3,4])
arr2=np.array([2,4,5])
rs=np.dot(arr1,arr2)
print(rs)

34


In [16]:
a=np.array([[20,30],[2,4]])
c=np.array([10,50])
np.linalg.solve(a,c)

array([-73.,  49.])

In [23]:
np.random.rand(2,10,2)

array([[[0.82666294, 0.34553713],
        [0.9192277 , 0.87856428],
        [0.10848491, 0.11599868],
        [0.7398051 , 0.47282249],
        [0.24882179, 0.85695261],
        [0.40805003, 0.46641549],
        [0.40779796, 0.9736091 ],
        [0.92802233, 0.65317196],
        [0.35409193, 0.53587257],
        [0.14552867, 0.68536392]],

       [[0.72995534, 0.70012542],
        [0.92476538, 0.40903069],
        [0.31412877, 0.46681732],
        [0.05671176, 0.46539467],
        [0.997553  , 0.89608534],
        [0.65575709, 0.52454779],
        [0.75508757, 0.33880278],
        [0.49930983, 0.79213364],
        [0.41744734, 0.65989773],
        [0.76306219, 0.49965945]]])

In [34]:
np.random.randint(1,100,size=10)

array([83, 59, 79, 36, 60, 39, 54, 36, 71, 93])